name: Bug report
description: Report something that is broken or incorrect.
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - MATLAB/Octave version:
    validations:
      required: false

