name: Feature request
description: Suggest an improvement or new feature.
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: What would you like to see added/changed?
    validations:
      required: true
